name: ict4farmers
description: UNFE ict for farmers

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.3.0+19

environment:
  sdk: ">=2.15.1 <3.0.0" 
  
dependencies:
  flutter:
    sdk: flutter
  flutx:
    path: ../flutx
  connectivity_plus: ^2.2.0
  dio: ^4.0.4

  # Base Dependencies
  cupertino_icons: ^1.0.3
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  google_fonts: 2.2.0
  path_provider: ^2.0.9
  cached_network_image: ^3.2.0
  flutter_form_builder: ^7.0.0
  form_builder_validators: ^7.2.0
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  shimmer: ^2.0.0
  google_maps_flutter: ^2.0.3
  image_picker: ^0.8.4+11
  geolocator: ^8.0.3
  url_launcher: ^6.0.20
  flutter_native_splash: ^2.1.6


  #(Syncfusion Flutter packages - Charts, Calendar, ETC.)
  syncfusion_flutter_charts: ^19.4.38
  onesignal_flutter: ^3.3.2
  sms_autofill: ^2.2.0
  #youtube_player_flutter: ^8.0.0
  #flutter_sound: ^8.3.9
  #assets_audio_player: ^3.0.3+3


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.2
  build_runner: ^2.1.7




  # Icons
  material_design_icons_flutter: 5.0.5955-rc.1
  flutter_feather_icons: ^2.0.0+1


  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:


    #Map Styles
    - assets/map/

    #Brand
    - assets/brand/

    #Languages
    - assets/lang/

    #Icons
    - assets/icons/

    #Other
    - assets/other/
    - assets/project/
    - assets/project/wizard/
    - assets/project/switcher_bg.jpg

    #main-branch